version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
